name: AdvancedServerListIcons
version: 1.1
main: com.me4502.advancedserverlisticons.AdvancedServerListIconsSpigot
authors: [Me4502]
description: Advanced Server List Icons for Spigot
api-version: 1.13
depend: [Vault]